# The sequence of triangle numbers is generated by adding the natural numbers. 
# So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
# We can see that 28 is the first triangle number to have over five divisors.
# What is the value of the first triangle number to have over five hundred divisors?

def delitelji(n):
    """ Vrne delitelje števila n. """
    st = 0
    for i in range(1, round((n+1) ** (1/2))):
        if n % i == 0:
            st += 1
            if i != n / i:
                st += 1
    return st



def trikotnisko(n):
    vsota = 0
    for i in range(1, n):
        vsota += i
    return vsota

print(delitelji(trikotnisko(20000)))

n = 200
while delitelji(trikotnisko(n)) < 500:
    n += 1
    print(trikotnisko(n))
